dist: xenial
addons:
  apt:
    update: true
    packages:
    - zlib1g-dev
language: cpp
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd packetq-[0-9]*
  - mkdir build
  - cd build
  - ../configure
  - make
  - make test
  - src/packetq -v
